name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

    steps:
      - name: Setup pnpm + Turborepo 🏗
        uses: cerberauth/ci/actions/pnpm-turbo-setup@main
        with:
          fetch-depth: 0
          registry-url: https://npm.pkg.github.com

      - name: Build packages
        run: pnpm turbo run build
        env:
          TURBO_TELEMETRY_DISABLED: 1

      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          version: pnpm version-packages
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
